---
- name: Resolvconf replacement play
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute as root
      become: yes
      block:
        - name: Install dnsmasq
          apt:
            name: dnsmasq
            state: latest

        - name: Disable and stop resolvconf and systemd-resolved services
          ignore_errors: yes
          systemd:
            name: "{{ dns_service }}"
            enabled: no
            state: stopped
          loop:
            - resolvconf
            - systemd-resolved
          loop_control:
            loop_var: dns_service

        - name: Uninstall resolvconf
          apt:
            name: resolvconf
            state: absent
          
        - name: Template DNS configuration files
          template:
            src: './templates/{{ dns_config }}.j2'
            dest: "/etc/{{ dns_config }}"
          loop:
            - dnsmasq.conf
            - resolv.conf
          loop_control:
            loop_var: dns_config
        
        - name: Bounce dnsmasq service
          changed_when: no
          systemd:
            name: dnsmasq
            enabled: yes
            state: restarted
...