---
- name: Add default greeting to host
  hosts: all
  gather_facts: no
  tasks:
  - name: Set variable for use in template
    set_fact:
      global_vm_shortname: "{{ shortname }}"

  - name: Gather ansible_env fact
    setup:
      filter: ansible_env

  - name: Add default greeting
    become: yes
    block:
      - name: "Template greeting to host"
        template:
          src: './roles/global/templates/greeting.sh.j2'
          dest: '/etc/greeting.sh'
          mode: '0755'

      - name: "Add greeting execution line to profiles"
        lineinfile:
          line: "/bin/bash /etc/greeting.sh"
          path: "{{ profile_path }}"
          create: yes
        loop:
          - "/etc/skel/.profile"
          - "{{ ansible_env.HOME }}/.profile"
        loop_control:
          loop_var: profile_path