---
- name: Resolvconf play
  hosts: all
  tasks:
    - name: Execute as root
      become: yes
      block:
        - name: Install resolvconf
          apt:
            name: resolvconf
            state: latest

        - name: Enable and start resolvconf service
          systemd:
            name: resolvconf.service
            enabled: yes
            state: started

        - name: Insert entries into resolvconf head
          lineinfile:
            path: '/etc/resolvconf/resolv.conf.d/head'
            line: "{{ item }}"
          loop:
            - "search yuriel.net"
            - "nameserver 172.16.0.30"
            - "nameserver 172.16.0.31"
            - "nameserver 8.8.8.8"

        - name: Update changes
          shell: "resolvconf --enable-updates && resolvconf -u"
