---
- name: Global VM provisioning play
  hosts: all
  gather_facts: no
  vars:
    ansible_user: vagrant
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: '/home/vagrant/.ssh/ansible/id_ansible'

  roles:
    - role: global
      tags:
        - template-vm

    - role: clone 
      when: ('template-vm' not in ansible_run_tags)
    
    - role: dns_server
      tags: dns-server
    
    - role: dev_master
      tags: dev-master
    
    - role: mysql_install
      tags: db-mysql

    - role: game_server
      tags: game-server

...
