---
- name: Insert Ansible public key onto host
  hosts: all
  vars:
    # These are actually fine to put on git.
    # The VMs are set to accept a password SSH only from the internal network.
    # Any external SSHs must be performed by private key.
    ansible_ssh_pass: vagrant
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: "Copy Ansible public key onto target"
      copy:
        src: "/home/vagrant/id_ansible.pub"
        dest: "/home/vagrant/.ssh/id_ansible.pub"

    - name: "Add key to authorized hosts"
      shell: "cat /home/vagrant/.ssh/id_ansible.pub >> /home/vagrant/.ssh/authorized_keys"

...