---
- name: Insert Ansible public key onto host
  hosts: all
  vars:
    ansible_ssh_pass: vagrant
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: "Copy Ansible public key onto target"
      copy:
        src: "/home/vagrant/id_ansible.pub"
        dest: "/home/vagrant/.ssh/id_ansible.pub"

    - name: "Add key to authorized hosts"
      shell: "cat /home/vagrant/.ssh/id_ansible.pub >> /home/vagrant/.ssh/authorized_keys"

- name: Global VM provisioning play
  hosts: all
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: '/home/vagrant/id_ansible'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: global
      tags:
        - general
        - game-server
    
    - role: dev_master
      tags: dev-master
    
    - role: mysql_install
      tags: db-mysql

    - role: game_server
      tags: game-server

...