---
- name: Check for ZeroTier install
  changed_when: no
  failed_when: no
  shell: 'which zerotier-one'
  register: gs_ztinstall

- name: Install ZeroTier One
  when: 
    - gs_install_zerotier
    - gs_ztinstall['stdout'] == ''
  block:
    # environment variables are a pain on linux for now, i'll stick to files
    - name: Look up variables from secrets
      ignore_errors: yes
      include_vars:
        file: '../../../private/secrets.yml'

    - name: Fetch ZeroTier git repository
      retries: 5
      delay: 3
      git:
        accept_hostkey: yes
        repo: 'https://github.com/zerotier/ZeroTierOne.git'
        dest: '/tmp/ZeroTierOne'

    - name: Build ZeroTier from source
      make:
        chdir: '/tmp/ZeroTierOne'

    - name: Install ZeroTier binaries
      make:
        chdir: '/tmp/ZeroTierOne'
        target: install
      become: yes
    
    - name: Determine ZeroTier install
      shell: which zerotier-one
      changed_when: false
      register: gs_zt_which
    
    - name: Add ZeroTier One as systemd service
      template:
        src: zerotier.service.j2
        dest: /etc/systemd/system/zerotier.service
      become: yes
    
    - name: Start ZeroTier service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: zerotier.service
      become: yes
    
    - name: Generate ZeroTier identity
      shell: "zerotier-one -i generate"
      changed_when: no
    
    - name: Join ZeroTier network specified in secrets
      shell: "zerotier-one -q -j join {{ gs_zt_network }}"
      when: gs_zt_network is defined
      become: yes
      changed_when: no

    - name: Fetch ZeroTier IP when available
      when: gs_zt_network is defined
      copy:
        src: fetch-ip.sh
        dest: /tmp/fetch-ip.sh
        mode: '0777'
        
    - name: Launch background script for fetching ZeroTier IP
      when: gs_zt_network is defined
      shell:
        cmd: nohup /tmp/fetch-ip.sh &
      become: yes

- name: Fail if ZeroTier is not to be installed and a server IP has not been provided
  when:
    - not gs_install_zerotier
    - gs_server_ip != "update"
    - gs_server_ip == "None" or not gs_server_ip | ipv4('address')
  fail:
    msg: "This role requires either that ZeroTier gets installed or that you provide it a valid IP to bind the server to"

- name: Write server address to file in case ZeroTier should not be installed
  when:
    - not gs_install_zerotier
    - gs_server_ip != 'update'
  shell: "echo {{ gs_server_ip | ipv4('address') }} > /etc/server-ip.txt"
  become: yes
