---
- name: Install ZeroTier One
  when: 
    - gs_install_zerotier
    - gs_server_ip != "update"
  include_role:
    name: 'zerotier'


- name: Assert that a valid server IP has been given should ZeroTier not be installed
  when:
    - not gs_install_zerotier
    - gs_server_ip != "update"
  assert:
    that: gs_server_ip | ipv4('address') | bool
    quiet: yes
    fail_msg: "This role requires either that ZeroTier gets installed or that you provide it a valid IP to bind the server to"

