---
- name: Include global tasks
  become: yes
  import_tasks: global.yml

- name: Include Terraria server tasks
  when: (gs_game | lower == "terraria")
  include_tasks: terraria.yml

- name: Include Minecraft server tasks
  when: (gs_game | lower == "minecraft")
  include_tasks: minecraft.yml

# - name: Include Starbound server tasks
#   import_tasks: starbound.yml
#   become: yes
#   when: (gs_game | lower == "starbound")
