---
- name: Ensure xz-utils is installed
  apt:
    name: 'xz-utils'
    state: latest
    update_cache: yes

- name: Warn user about long setup
  debug:
    msg: "Warning: Ansible will now install apt and deb packages. This may take a while!"

- name: Install apt packages
  apt:
    name: "{{ devinstall_apt_pkg }}"
    state: latest
  when: devinstall_packages['apt'] != []
  retries: 3
  delay: 10

  # place in a loop so we can keep track of what was installed
  loop: "{{ devinstall_packages['apt'] | list }}"
  loop_control:
    loop_var: "devinstall_apt_pkg"

- name: Install deb packages
  apt:
    deb: "{{ devinstall_deb.value }}"
    state: present
  loop: "{{ devinstall_packages['deb'] | dict2items }}"
  loop_control:
    loop_var: devinstall_deb
  retries: 3
  delay: 10
...
