---
- name: Assert that we're running on a supported host
  assert:
    that: ansible_distribution | lower in ["ubuntu", "linux mint"]
    quiet: yes
    fail_msg: "Unsupported OS ({{ ansible_distribution }}), only Ubuntu and Linux Mint are supported!"

- name: Import tasks
  when: not devinstall_skiptovscode is defined or not devinstall_skiptovscode
  become: yes
  block:
    - name: Warn user about long setup
      when: devinstall_add_lxde | default(true) | bool
      debug:
        msg: 'Warning: Ansible will now install Desktop packages. This will take a while!'
 
    - name: Make sure Desktop GUI packages are present and up to date
      when: devinstall_add_lxde | default(true) | bool
      apt:
        name: ['lxde', 'lxde-core', 'lxde-icon-theme', 'yaru-theme-gtk', 'yaru-theme-icon']
        state: present

    - name: Import add keys task
      import_tasks: 'add_keys.yml'

    - name: Import install task
      import_tasks: 'install.yml'
    
    - name: Import remote desktop tasks
      import_tasks: 'install_remdesk.yml'

- name: Install VS Code extensions
  when: "'code' in devinstall_packages['apt'] or 'vscode' in devinstall_packages['deb'].keys()"
  become: yes
  become_user: vagrant
  import_tasks: 'vscode_extensions.yml'
...
