---
- name: Fail on non-Ubuntu host
  fail:
    msg: This role only supports Ubuntu hosts
  when: ansible_lsb['id'] | lower != "ubuntu"

- name: Import tasks
  when: not devinstall_skiptovscode is defined or not devinstall_skiptovscode
  become: yes
  block:
    - name: Make sure Desktop GUI packages are present and up to date
      apt:
        name: 'ubuntu-desktop'
        state: latest

    - name: Import add keys task
      import_tasks: 'add_keys.yml'

    - name: Import install task
      import_tasks: 'install.yml'
    
    - name: Import x11vnc tasks
      import_tasks: 'install_x11vnc.yml'

- name: Install VS Code extensions
  when: "'code' in devinstall_packages['apt'] or 'vscode' in devinstall_packages['deb'].keys()"
  become: yes
  become_user: vagrant
  import_tasks: 'vscode_extensions.yml'
...
