---
# vars file for global_ubuntu

global_python:
  url: 'https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tar.xz'
  dependencies:
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev

global_python_dir: "{{ global_python['url'] | basename | regex_replace('\\.t.*$', '') }}"
global_python_latest: "{{ global_python_dir.split('-')[-1] | regex_replace('\\.', '') | int }}"

global_linux_essentials:
  - g++
  - gcc
  - make
  - tar
  - zip
  - unzip
  - iptables
  - ufw
  - tmux
