---
- name: Ensure essential tools are present
  package:
    name: "{{ global_lx_essential }}"
    state: "{{ 'latest' if 'ubuntu' in ansible_lsb['id'] | lower else 'present' }}"
  loop: "{{ global_linux_essentials }}"
  loop_control:
    loop_var: global_lx_essential

- name: Import VM aesthetic configuration tasks
  import_tasks: 'vm_specs.yml'

- name: Import DNS service tasks
  when: ('DNS' not in global_vm_shortname)
  import_tasks: 'configure_dns.yml'


- name: Make sure /etc/boot_scripts exists
  become: yes
  file:
    path: '/etc/boot_scripts'


- name: 'Template IP regeneration (DHCP) script for interface #2 to /etc/boot_scripts'
  become: yes
  template:
    src: 'regen-dhcp.sh.j2'
    dest: '/etc/boot_scripts/regen-dhcp.sh'
    mode: '0755'


- name: 'Template IP regeneration as a systemd service'
  become: yes
  template:
    src: 'regen-dhcp.service.j2'
    dest: '/etc/systemd/system/regen-dhcp.service'
  notify: 'Regenerate IP in 5 seconds'


- name: Enable IP regeneration service on boot
  become: yes
  service:
    name: regen-dhcp
    enabled: yes


- name: Disable IPv6 for good
  become: yes
  replace:
    dest: '/etc/default/grub'
    replace: '\1 ipv6.disable=1'
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*)'

- name: Update grub
  become: yes
  shell: 'update-grub'
  changed_when: no

# much simpler python update workaround
- name: Install Python 3.9
  block:
    - name: Fetch Python package
      package:
        name: python3.9
        state: "{{ 'latest' if 'ubuntu' in ansible_lsb['id'] | lower else 'present' }}"

    - name: Add Python alias to all users
      lineinfile:
        path: '/etc/bash.bashrc'
        line: "alias python='/usr/bin/python3.9'"
