---
- name: Ensure essential tools are present
  package:
    name: "{{ global_lx_essential }}"
    state: "{{ 'latest' if 'ubuntu' in ansible_lsb['id'] | lower else 'present' }}"
  loop: "{{ global_linux_essentials }}"
  loop_control:
    loop_var: global_lx_essential

- name: Import VM aesthetic configuration tasks
  import_tasks: 'vm_specs.yml'

- name: Import DNS service tasks
  when: ('DNS' not in global_vm_shortname)
  import_tasks: 'configure_dns.yml'

- name: Import IPv6 disable tasks
  import_tasks: 'disable_ipv6.yml'

# much simpler python update workaround
- name: Install Python 3.9
  block:
    - name: Fetch Python package
      package:
        name: python3.9
        state: "{{ 'latest' if 'ubuntu' in ansible_lsb['id'] | lower else 'present' }}"

    - name: Add Python alias to all users
      lineinfile:
        path: '/etc/bash.bashrc'
        line: "alias python='/usr/bin/python3.9'"
