---
# tasks file for global
- name: Gather facts needed
  setup:
    filter: "{{ global_fact }}"
  loop:
    - ansible_distribution
    - ansible_env
  loop_control:
    loop_var: global_fact

- name: Figure out which OS family we're dealing with
  import_tasks: parse_os.yml
  run_once: true

- name: Import Linux global tasks, if applicable
  import_tasks: linux_global.yml
  when: global_os == "linux"
  become: yes

- name: Import Windows global tasks, if applicable
  import_tasks: win_global.yml
  when: global_os == "windows"
  become: yes
