---
- name: "Template greeting to host"
  template:
    src: greeting.sh.j2
    dest: '/etc/greeting.sh'
    mode: '0755'

- name: "Add greeting execution line to profiles"
  lineinfile:
    line: "/bin/bash /etc/greeting.sh"
    path: "{{ global_profile_path }}"
    create: yes
  loop:
    - "/etc/skel/.profile"
    - "/home/vagrant/.profile"
  loop_control:
    loop_var: global_profile_path

- name: "Set hostname"
  hostname:
    name: "{{ global_vm_hostname }}"

- name: "Set .bashrc for all users"
  template:
    src: bashrc.j2
    dest: "{{ global_bashrc_path }}"
  loop:
    - '/etc/skel/.bashrc'
    - '/home/vagrant/.bashrc'
  loop_control:
    loop_var: global_bashrc_path
