---
- name: Gather distro fact
  setup:
    filter: "ansible_distribution"

- name: "Template greeting to host"
  template:
    src: greeting.sh.j2
    dest: '{{ "/etc/update-motd.d/99-greeting" if ansible_distribution | lower == "ubuntu" else "/etc/profile.d/greeting.sh" }}'
    mode: '0755'

- name: "Set hostname"
  hostname:
    name: "{{ global_vm_hostname }}"

- name: "Set .bashrc for all users"
  template:
    src: bashrc.j2
    dest: "{{ global_bashrc_path }}"
  loop:
    - '/etc/skel/.bashrc'
    - '/home/vagrant/.bashrc'
    - '/root/.bashrc'
  loop_control:
    loop_var: global_bashrc_path
