---
- name: "Template greeting to host"
  template:
    src: greeting.sh.j2
    dest: '{{ "/etc/update-motd.d/99-greeting" if ansible_distribution | lower in ["ubuntu", "linux mint"] else "/etc/profile.d/greeting.sh" }}'
    mode: '0755'

- name: "Set hostname"
  hostname:
    name: "{{ global_vm_hostname }}"

- name: "Set .bashrc for all users"
  template:
    src: "bashrc-{{ 'ubuntu' if ansible_distribution | lower in ['ubuntu', 'linux mint'] else ansible_distribution | lower }}.j2"
    dest: "{{ global_bashrc_path }}"
  loop:
    - '/etc/skel/.bashrc'
    - '{{ ansible_env.HOME }}/.bashrc'
  loop_control:
    loop_var: global_bashrc_path

- name: "Set .bashrc for root user"
  vars:
    bashrc_user: 'root'
  template:
    src: "bashrc-{{ 'ubuntu' if ansible_distribution | lower in ['ubuntu', 'linux mint'] else ansible_distribution | lower }}.j2"
    dest: '/root/.bashrc'
