---
# tasks file for clone
- name: Determine OS
  import_tasks: 'parse_os.yml'

- name: Do Linux routines
  when: global_os == 'linux'
  become: yes
  block:
    - name: Gather distro name fact
      setup:
        filter: "ansible_distribution"

    - name: "Template greeting to host"
      template:
        src: greeting.sh.j2
        dest: '{{ "/etc/update-motd.d/99-greeting" if ansible_distribution | lower == "ubuntu" else "/etc/profile.d/greeting.sh" }}' 
        mode: '0755'

    - name: "Set hostname"
      hostname:
        name: "{{ global_vm_hostname }}"

    - name: "Set .bashrc for all users"
      template:
        src: bashrc.j2
        dest: "{{ global_bashrc_path }}"
      loop:
        - '/etc/skel/.bashrc'
        - '/home/vagrant/.bashrc'
      loop_control:
        loop_var: global_bashrc_path

    - name: "Set .bashrc for root user"
      vars:
        bashrc_user: 'root'
      template:
        src: bashrc.j2
        dest: '/root/.bashrc'
   
    - name: Warn user about long task
      debug:
        msg: "Warning: Ansible will now update apt cache and upgrade all the packages it can. This might take a while!"

    - name: Update apt cache and upgrade all packages
      apt:
        upgrade: 'safe'
        update_cache: yes
