---
# tasks file for dns_server
- name: Gather distribution fact
  setup:
    filter: ansible_distribution

- name: Install BIND
  become: yes
  retries: 3
  delay: 3
  package:
    name: "{{ dns_server_package }}"
    state: present
  loop: "{{ dns_server_packages[(ansible_distribution | lower)] }}"
  loop_control:
    loop_var: dns_server_package


- name: Make sure dnsmasq is absent
  become: yes
  package:
    name: dnsmasq
    state: absent


- name: Include distro-specific install tasks
  import_tasks: "{{ ansible_distribution | lower }}.yml"
