---
# tasks file for dns_server
- name: Gather necessary facts
  setup:
    filter: "{{ dns_server_fact }}"
  loop:
    - ansible_distribution
    - ansible_date_time
  loop_control:
    loop_var: dns_server_fact

- name: Install BIND
  become: yes
  retries: 3
  delay: 3
  package:
    name: "{{ dns_server_package }}"
    state: present
  loop: "{{ dns_server_packages[(ansible_distribution | lower)] }}"
  loop_control:
    loop_var: dns_server_package


- name: Make sure dnsmasq is absent
  become: yes
  package:
    name: dnsmasq
    state: absent


- name: Include distro-specific install tasks
  include_tasks:
    file: "{{ ansible_distribution | lower }}.yml"
    apply:
      become: yes
