---
- hosts: terraria
  vars:
    gs_overwrite: yes
    gs_type: terraria
    gs_install_zerotier: false
    gs_server_ip: update
  
  pre_tasks:
    - name: Load variables
      ignore_errors: yes
      include_vars:
        file: "/home/vagrant/ansible/private/{{ ansible_host }}_terraria-variables.yml"

    - name: Fetch install link
      block:
        - name: Find latest version install link
          run_once: yes
          shell: "links -source https://terraria.org/ | grep -i \"pc dedicated\" | head -n 1 | grep -o \"'.*'\" | grep -o \"[^']*\""
          register: gs_terraria_linkdir
          changed_when: no

        - name: Put link together
          set_fact:
            gs_terraria_link: "https://terraria.org{{ gs_terraria_linkdir['stdout'] }}"

  roles:
    - role: game_server
      become: yes
      when: gs_terraria_link != gs_terraria_curlink
...